server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_db_01?serverTimezone=UTC
      username: root
      password: admin123
mybatis-plus:
  global-config:
    db-config:
      table-prefix: m_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

